{{- if not .Values.postgresql.existingSecret -}}
{{- $pgDsn := .Values.postgresql.dsn -}}
{{- if not $pgDsn -}}
{{- $pgDsn = printf "host=%s user=%s password=%s dbname=%s port=%s sslmode=%s TimeZone=UTC" .Values.postgresql.host .Values.postgresql.user .Values.postgresql.password .Values.postgresql.database (toString .Values.postgresql.port) .Values.postgresql.sslMode -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goflow.envSecretName" . }}
  labels:
    {{- include "goflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  PG_DSN: {{ $pgDsn | quote }}
  AUTH_INTROSPECTION_CLIENT_SECRET: {{ .Values.iam.auth.introspectionClientSecret | quote }}
{{- end }}
{{- if and .Values.zitadel.enabled (not .Values.zitadel.existingSecret) }}
---
{{- $zitadelPostgresHost := printf "%s-zitadel-postgresql" (include "goflow.fullname" .) -}}
{{- $zitadelDsn := printf "postgres://%s:%s@%s:5432/%s?sslmode=disable" .Values.zitadel.postgresql.user .Values.zitadel.postgresql.password $zitadelPostgresHost .Values.zitadel.postgresql.database -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goflow.zitadelSecretName" . }}
  labels:
    {{- include "goflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZITADEL_MASTERKEY: {{ .Values.zitadel.masterkey | quote }}
  ZITADEL_ADMIN_PASSWORD: {{ .Values.zitadel.bootstrap.adminPassword | quote }}
  ZITADEL_POSTGRES_PASSWORD: {{ .Values.zitadel.postgresql.password | quote }}
  ZITADEL_DATABASE_POSTGRES_DSN: {{ $zitadelDsn | quote }}
{{- end }}
