iam:
  mode: zitadel
  providerName: ZITADEL
  auth:
    issuerInternalUrl: ""
    issuerPublicUrl: "https://iam.artificialflow.example.io"
    clientId: workflow-backend
    tokenMode: introspection
    introspectionUrl: ""
    introspectionClientId: ""
    introspectionClientSecret: ""
    introspectionAuthMethod: basic
    claimSubjectPath: sub
    claimRolesPath: roles,urn:zitadel:iam:org:project:roles,groups
    claimScopesPath: scope,scp
    claimTenantPath: urn:zitadel:iam:user:resourceowner:id
    claimEmailPath: email
    claimNamePath: name
    enforceAudience: true
    allowInsecureIssuer: true
  frontend:
    oidcAuthority: "https://iam.artificialflow.example.io"
    oidcClientId: ""
    oidcClientIdFile: ""

zitadel:
  enabled: true
  publicUrl: "https://iam.artificialflow.example.io"
  externalDomain: iam.artificialflow.example.io
  externalPort: 443
  externalSecure: true
  masterkey: MasterkeyNeedsToHave32Characters
  bootstrap:
    accessTokenLifetime: 900s
    frontendUrl: "https://app.artificialflow.example.io"
    adminUsername: admin
    adminPassword: "change-me"
    adminEmail: admin@example.com
  ingress:
    enabled: true
    host: iam.artificialflow.example.io
    tls:
      enabled: true
      secretName: artificialflow-iam-tls

ingress:
  enabled: true
  host: app.artificialflow.example.io
  tls:
    enabled: true
    secretName: artificialflow-tls
