services:
  app:
    image: ${WORKFLOWSA_IMAGE_REGISTRY:-workflowsa}/workflow-command:${WORKFLOWSA_IMAGE_TAG:-0.1.0}
    build: !reset null

  workflow-runtime:
    image: ${WORKFLOWSA_IMAGE_REGISTRY:-workflowsa}/workflow-runtime:${WORKFLOWSA_IMAGE_TAG:-0.1.0}
    build: !reset null

  workflow-query:
    image: ${WORKFLOWSA_IMAGE_REGISTRY:-workflowsa}/workflow-query:${WORKFLOWSA_IMAGE_TAG:-0.1.0}
    build: !reset null

  sync-worker:
    image: ${WORKFLOWSA_IMAGE_REGISTRY:-workflowsa}/sync-worker:${WORKFLOWSA_IMAGE_TAG:-0.1.0}
    build: !reset null

  frontend:
    image: ${WORKFLOWSA_IMAGE_REGISTRY:-workflowsa}/frontend:${WORKFLOWSA_IMAGE_TAG:-0.1.0}
    build: !reset null
