iam:
  mode: zitadel
  providerName: ZITADEL
  auth:
    issuerInternalUrl: ""
    issuerPublicUrl: "https://iam.goflow.example.com"
    clientId: workflow-backend
    tokenMode: jwt
    introspectionUrl: ""
    introspectionClientId: ""
    introspectionClientSecret: ""
    introspectionAuthMethod: basic
    claimSubjectPath: sub
    claimRolesPath: roles,urn:zitadel:iam:org:project:roles,groups
    claimScopesPath: scope,scp
    claimTenantPath: urn:zitadel:iam:user:resourceowner:id
    claimEmailPath: email
    claimNamePath: name
    enforceAudience: false
    allowInsecureIssuer: true
  frontend:
    oidcAuthority: "https://iam.goflow.example.com"
    oidcClientId: ""
    oidcClientIdFile: /goflow/bootstrap/goflow-frontend-client-id

zitadel:
  enabled: true
  publicUrl: "https://iam.goflow.example.com"
  externalDomain: iam.goflow.example.com
  externalPort: 443
  externalSecure: true
  masterkey: MasterkeyNeedsToHave32Characters
  bootstrap:
    frontendUrl: "https://goflow.example.com"
    adminUsername: admin
    adminPassword: "change-me"
    adminEmail: admin@example.com
  ingress:
    enabled: true
    host: iam.goflow.example.com
    tls:
      enabled: true
      secretName: goflow-iam-tls

ingress:
  enabled: true
  host: goflow.example.com
  tls:
    enabled: true
    secretName: goflow-tls
