apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgo.queryServiceName" . }}
  labels:
    {{- include "flowgo.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
spec:
  type: {{ .Values.query.service.type }}
  ports:
    - name: http
      port: {{ .Values.query.service.port }}
      targetPort: http
  selector:
    {{- include "flowgo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowgo.fullname" . }}-query
  labels:
    {{- include "flowgo.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
spec:
  replicas: {{ .Values.replicaCount.query }}
  selector:
    matchLabels:
      {{- include "flowgo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: query
  template:
    metadata:
      labels:
        {{- include "flowgo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: query
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "flowgo.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: workflow-query
          image: "{{ .Values.images.query.repository }}:{{ .Values.images.query.tag }}"
          imagePullPolicy: {{ .Values.images.query.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ include "flowgo.envConfigName" . }}
          env:
            - name: AUTH_INTROSPECTION_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "flowgo.envSecretName" . }}
                  key: AUTH_INTROSPECTION_CLIENT_SECRET
                  optional: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.query.resources | nindent 12 }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
