{{- if .Values.runtime.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowgo.fullname" . }}-runtime
  labels:
    {{- include "flowgo.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
spec:
  replicas: {{ .Values.replicaCount.runtime }}
  selector:
    matchLabels:
      {{- include "flowgo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: runtime
  template:
    metadata:
      labels:
        {{- include "flowgo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: runtime
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "flowgo.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: workflow-runtime
          image: "{{ .Values.images.runtime.repository }}:{{ .Values.images.runtime.tag }}"
          imagePullPolicy: {{ .Values.images.runtime.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "flowgo.envConfigName" . }}
          env:
            - name: RUNTIME_ENABLED
              value: {{ .Values.runtime.env.runtimeEnabled | quote }}
            - name: PG_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "flowgo.envSecretName" . }}
                  key: {{ .Values.postgresql.existingSecretKey | default "PG_DSN" }}
          resources:
            {{- toYaml .Values.runtime.resources | nindent 12 }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
