// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: backend/api/proto/job_worker_service.proto

package workflowapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JobWorkerServiceClient is the client API for JobWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobWorkerServiceClient interface {
	// ActivateJobs polls for jobs available for a specific worker/type.
	// It returns a stream of jobs to allow for immediate pushing if long-polling.
	// For MVP, request/response is fine, but stream is future-proof.
	ActivateJobs(ctx context.Context, in *ActivateJobsRequest, opts ...grpc.CallOption) (*ActivateJobsResponse, error)
	// CompleteJob marks a job as completed with variables.
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error)
	// FailJob marks a job as failed with retries.
	FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*FailJobResponse, error)
}

type jobWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobWorkerServiceClient(cc grpc.ClientConnInterface) JobWorkerServiceClient {
	return &jobWorkerServiceClient{cc}
}

func (c *jobWorkerServiceClient) ActivateJobs(ctx context.Context, in *ActivateJobsRequest, opts ...grpc.CallOption) (*ActivateJobsResponse, error) {
	out := new(ActivateJobsResponse)
	err := c.cc.Invoke(ctx, "/goflow.api.v1.JobWorkerService/ActivateJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobWorkerServiceClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error) {
	out := new(CompleteJobResponse)
	err := c.cc.Invoke(ctx, "/goflow.api.v1.JobWorkerService/CompleteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobWorkerServiceClient) FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*FailJobResponse, error) {
	out := new(FailJobResponse)
	err := c.cc.Invoke(ctx, "/goflow.api.v1.JobWorkerService/FailJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobWorkerServiceServer is the server API for JobWorkerService service.
// All implementations must embed UnimplementedJobWorkerServiceServer
// for forward compatibility
type JobWorkerServiceServer interface {
	// ActivateJobs polls for jobs available for a specific worker/type.
	// It returns a stream of jobs to allow for immediate pushing if long-polling.
	// For MVP, request/response is fine, but stream is future-proof.
	ActivateJobs(context.Context, *ActivateJobsRequest) (*ActivateJobsResponse, error)
	// CompleteJob marks a job as completed with variables.
	CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error)
	// FailJob marks a job as failed with retries.
	FailJob(context.Context, *FailJobRequest) (*FailJobResponse, error)
	mustEmbedUnimplementedJobWorkerServiceServer()
}

// UnimplementedJobWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobWorkerServiceServer struct {
}

func (UnimplementedJobWorkerServiceServer) ActivateJobs(context.Context, *ActivateJobsRequest) (*ActivateJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateJobs not implemented")
}
func (UnimplementedJobWorkerServiceServer) CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedJobWorkerServiceServer) FailJob(context.Context, *FailJobRequest) (*FailJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailJob not implemented")
}
func (UnimplementedJobWorkerServiceServer) mustEmbedUnimplementedJobWorkerServiceServer() {}

// UnsafeJobWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobWorkerServiceServer will
// result in compilation errors.
type UnsafeJobWorkerServiceServer interface {
	mustEmbedUnimplementedJobWorkerServiceServer()
}

func RegisterJobWorkerServiceServer(s grpc.ServiceRegistrar, srv JobWorkerServiceServer) {
	s.RegisterService(&JobWorkerService_ServiceDesc, srv)
}

func _JobWorkerService_ActivateJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServiceServer).ActivateJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goflow.api.v1.JobWorkerService/ActivateJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServiceServer).ActivateJobs(ctx, req.(*ActivateJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobWorkerService_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServiceServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goflow.api.v1.JobWorkerService/CompleteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServiceServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobWorkerService_FailJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServiceServer).FailJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goflow.api.v1.JobWorkerService/FailJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServiceServer).FailJob(ctx, req.(*FailJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobWorkerService_ServiceDesc is the grpc.ServiceDesc for JobWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goflow.api.v1.JobWorkerService",
	HandlerType: (*JobWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateJobs",
			Handler:    _JobWorkerService_ActivateJobs_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _JobWorkerService_CompleteJob_Handler,
		},
		{
			MethodName: "FailJob",
			Handler:    _JobWorkerService_FailJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/api/proto/job_worker_service.proto",
}
