// source: job_worker_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.flowgo.api.v1.ActivateJobsRequest', null, global);
goog.exportSymbol('proto.flowgo.api.v1.ActivateJobsResponse', null, global);
goog.exportSymbol('proto.flowgo.api.v1.CompleteJobRequest', null, global);
goog.exportSymbol('proto.flowgo.api.v1.CompleteJobResponse', null, global);
goog.exportSymbol('proto.flowgo.api.v1.FailJobRequest', null, global);
goog.exportSymbol('proto.flowgo.api.v1.FailJobResponse', null, global);
goog.exportSymbol('proto.flowgo.api.v1.Job', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flowgo.api.v1.ActivateJobsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.flowgo.api.v1.ActivateJobsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.flowgo.api.v1.ActivateJobsRequest.displayName = 'proto.flowgo.api.v1.ActivateJobsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flowgo.api.v1.ActivateJobsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.flowgo.api.v1.ActivateJobsResponse.repeatedFields_, null);
};
goog.inherits(proto.flowgo.api.v1.ActivateJobsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.flowgo.api.v1.ActivateJobsResponse.displayName = 'proto.flowgo.api.v1.ActivateJobsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flowgo.api.v1.Job = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.flowgo.api.v1.Job, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.flowgo.api.v1.Job.displayName = 'proto.flowgo.api.v1.Job';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flowgo.api.v1.CompleteJobRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.flowgo.api.v1.CompleteJobRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.flowgo.api.v1.CompleteJobRequest.displayName = 'proto.flowgo.api.v1.CompleteJobRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flowgo.api.v1.CompleteJobResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.flowgo.api.v1.CompleteJobResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.flowgo.api.v1.CompleteJobResponse.displayName = 'proto.flowgo.api.v1.CompleteJobResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flowgo.api.v1.FailJobRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.flowgo.api.v1.FailJobRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.flowgo.api.v1.FailJobRequest.displayName = 'proto.flowgo.api.v1.FailJobRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flowgo.api.v1.FailJobResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.flowgo.api.v1.FailJobResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.flowgo.api.v1.FailJobResponse.displayName = 'proto.flowgo.api.v1.FailJobResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.flowgo.api.v1.ActivateJobsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flowgo.api.v1.ActivateJobsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.ActivateJobsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    workerName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    jobType: jspb.Message.getFieldWithDefault(msg, 2, ""),
    maxJobs: jspb.Message.getFieldWithDefault(msg, 3, 0),
    timeoutMs: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flowgo.api.v1.ActivateJobsRequest}
 */
proto.flowgo.api.v1.ActivateJobsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flowgo.api.v1.ActivateJobsRequest;
  return proto.flowgo.api.v1.ActivateJobsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flowgo.api.v1.ActivateJobsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flowgo.api.v1.ActivateJobsRequest}
 */
proto.flowgo.api.v1.ActivateJobsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkerName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxJobs(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimeoutMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flowgo.api.v1.ActivateJobsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flowgo.api.v1.ActivateJobsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.ActivateJobsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkerName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getJobType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMaxJobs();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTimeoutMs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional string worker_name = 1;
 * @return {string}
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.getWorkerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.ActivateJobsRequest} returns this
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.setWorkerName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string job_type = 2;
 * @return {string}
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.getJobType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.ActivateJobsRequest} returns this
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.setJobType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 max_jobs = 3;
 * @return {number}
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.getMaxJobs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.ActivateJobsRequest} returns this
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.setMaxJobs = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 timeout_ms = 4;
 * @return {number}
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.getTimeoutMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.ActivateJobsRequest} returns this
 */
proto.flowgo.api.v1.ActivateJobsRequest.prototype.setTimeoutMs = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.flowgo.api.v1.ActivateJobsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flowgo.api.v1.ActivateJobsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.flowgo.api.v1.ActivateJobsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flowgo.api.v1.ActivateJobsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.ActivateJobsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobsList: jspb.Message.toObjectList(msg.getJobsList(),
    proto.flowgo.api.v1.Job.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flowgo.api.v1.ActivateJobsResponse}
 */
proto.flowgo.api.v1.ActivateJobsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flowgo.api.v1.ActivateJobsResponse;
  return proto.flowgo.api.v1.ActivateJobsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flowgo.api.v1.ActivateJobsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flowgo.api.v1.ActivateJobsResponse}
 */
proto.flowgo.api.v1.ActivateJobsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.flowgo.api.v1.Job;
      reader.readMessage(value,proto.flowgo.api.v1.Job.deserializeBinaryFromReader);
      msg.addJobs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flowgo.api.v1.ActivateJobsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flowgo.api.v1.ActivateJobsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flowgo.api.v1.ActivateJobsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.ActivateJobsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.flowgo.api.v1.Job.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Job jobs = 1;
 * @return {!Array<!proto.flowgo.api.v1.Job>}
 */
proto.flowgo.api.v1.ActivateJobsResponse.prototype.getJobsList = function() {
  return /** @type{!Array<!proto.flowgo.api.v1.Job>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.flowgo.api.v1.Job, 1));
};


/**
 * @param {!Array<!proto.flowgo.api.v1.Job>} value
 * @return {!proto.flowgo.api.v1.ActivateJobsResponse} returns this
*/
proto.flowgo.api.v1.ActivateJobsResponse.prototype.setJobsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.flowgo.api.v1.Job=} opt_value
 * @param {number=} opt_index
 * @return {!proto.flowgo.api.v1.Job}
 */
proto.flowgo.api.v1.ActivateJobsResponse.prototype.addJobs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.flowgo.api.v1.Job, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.flowgo.api.v1.ActivateJobsResponse} returns this
 */
proto.flowgo.api.v1.ActivateJobsResponse.prototype.clearJobsList = function() {
  return this.setJobsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flowgo.api.v1.Job.prototype.toObject = function(opt_includeInstance) {
  return proto.flowgo.api.v1.Job.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flowgo.api.v1.Job} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.Job.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    type: jspb.Message.getFieldWithDefault(msg, 3, ""),
    processInstanceKey: jspb.Message.getFieldWithDefault(msg, 4, 0),
    bpmnProcessId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    processDefinitionVersion: jspb.Message.getFieldWithDefault(msg, 6, 0),
    processDefinitionKey: jspb.Message.getFieldWithDefault(msg, 7, 0),
    elementInstanceKey: jspb.Message.getFieldWithDefault(msg, 8, 0),
    elementId: jspb.Message.getFieldWithDefault(msg, 9, ""),
    customHeadersMap: (f = msg.getCustomHeadersMap()) ? f.toObject(includeInstance, undefined) : [],
    worker: jspb.Message.getFieldWithDefault(msg, 11, ""),
    retries: jspb.Message.getFieldWithDefault(msg, 12, 0),
    deadline: jspb.Message.getFieldWithDefault(msg, 13, 0),
    variables: jspb.Message.getFieldWithDefault(msg, 14, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flowgo.api.v1.Job}
 */
proto.flowgo.api.v1.Job.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flowgo.api.v1.Job;
  return proto.flowgo.api.v1.Job.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flowgo.api.v1.Job} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flowgo.api.v1.Job}
 */
proto.flowgo.api.v1.Job.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProcessInstanceKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setBpmnProcessId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProcessDefinitionVersion(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProcessDefinitionKey(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setElementInstanceKey(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setElementId(value);
      break;
    case 10:
      var value = msg.getCustomHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorker(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRetries(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDeadline(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setVariables(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flowgo.api.v1.Job.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flowgo.api.v1.Job.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flowgo.api.v1.Job} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.Job.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getProcessInstanceKey();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getBpmnProcessId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getProcessDefinitionVersion();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getProcessDefinitionKey();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getElementInstanceKey();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getElementId();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCustomHeadersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(10, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getWorker();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getRetries();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getDeadline();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getVariables();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
};


/**
 * optional int64 key = 1;
 * @return {number}
 */
proto.flowgo.api.v1.Job.prototype.getKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setKey = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.flowgo.api.v1.Job.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string type = 3;
 * @return {string}
 */
proto.flowgo.api.v1.Job.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 process_instance_key = 4;
 * @return {number}
 */
proto.flowgo.api.v1.Job.prototype.getProcessInstanceKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setProcessInstanceKey = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string bpmn_process_id = 5;
 * @return {string}
 */
proto.flowgo.api.v1.Job.prototype.getBpmnProcessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setBpmnProcessId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 process_definition_version = 6;
 * @return {number}
 */
proto.flowgo.api.v1.Job.prototype.getProcessDefinitionVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setProcessDefinitionVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 process_definition_key = 7;
 * @return {number}
 */
proto.flowgo.api.v1.Job.prototype.getProcessDefinitionKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setProcessDefinitionKey = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 element_instance_key = 8;
 * @return {number}
 */
proto.flowgo.api.v1.Job.prototype.getElementInstanceKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setElementInstanceKey = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string element_id = 9;
 * @return {string}
 */
proto.flowgo.api.v1.Job.prototype.getElementId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setElementId = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * map<string, string> custom_headers = 10;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.flowgo.api.v1.Job.prototype.getCustomHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 10, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.clearCustomHeadersMap = function() {
  this.getCustomHeadersMap().clear();
  return this;};


/**
 * optional string worker = 11;
 * @return {string}
 */
proto.flowgo.api.v1.Job.prototype.getWorker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setWorker = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional int32 retries = 12;
 * @return {number}
 */
proto.flowgo.api.v1.Job.prototype.getRetries = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setRetries = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int64 deadline = 13;
 * @return {number}
 */
proto.flowgo.api.v1.Job.prototype.getDeadline = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setDeadline = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional string variables = 14;
 * @return {string}
 */
proto.flowgo.api.v1.Job.prototype.getVariables = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.Job} returns this
 */
proto.flowgo.api.v1.Job.prototype.setVariables = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flowgo.api.v1.CompleteJobRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.flowgo.api.v1.CompleteJobRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flowgo.api.v1.CompleteJobRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.CompleteJobRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobKey: jspb.Message.getFieldWithDefault(msg, 1, 0),
    workerName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    variables: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flowgo.api.v1.CompleteJobRequest}
 */
proto.flowgo.api.v1.CompleteJobRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flowgo.api.v1.CompleteJobRequest;
  return proto.flowgo.api.v1.CompleteJobRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flowgo.api.v1.CompleteJobRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flowgo.api.v1.CompleteJobRequest}
 */
proto.flowgo.api.v1.CompleteJobRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setJobKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkerName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVariables(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flowgo.api.v1.CompleteJobRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flowgo.api.v1.CompleteJobRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flowgo.api.v1.CompleteJobRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.CompleteJobRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobKey();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getWorkerName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVariables();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 job_key = 1;
 * @return {number}
 */
proto.flowgo.api.v1.CompleteJobRequest.prototype.getJobKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.CompleteJobRequest} returns this
 */
proto.flowgo.api.v1.CompleteJobRequest.prototype.setJobKey = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string worker_name = 2;
 * @return {string}
 */
proto.flowgo.api.v1.CompleteJobRequest.prototype.getWorkerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.CompleteJobRequest} returns this
 */
proto.flowgo.api.v1.CompleteJobRequest.prototype.setWorkerName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string variables = 3;
 * @return {string}
 */
proto.flowgo.api.v1.CompleteJobRequest.prototype.getVariables = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.CompleteJobRequest} returns this
 */
proto.flowgo.api.v1.CompleteJobRequest.prototype.setVariables = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flowgo.api.v1.CompleteJobResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.flowgo.api.v1.CompleteJobResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flowgo.api.v1.CompleteJobResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.CompleteJobResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flowgo.api.v1.CompleteJobResponse}
 */
proto.flowgo.api.v1.CompleteJobResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flowgo.api.v1.CompleteJobResponse;
  return proto.flowgo.api.v1.CompleteJobResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flowgo.api.v1.CompleteJobResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flowgo.api.v1.CompleteJobResponse}
 */
proto.flowgo.api.v1.CompleteJobResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flowgo.api.v1.CompleteJobResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flowgo.api.v1.CompleteJobResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flowgo.api.v1.CompleteJobResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.CompleteJobResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flowgo.api.v1.FailJobRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.flowgo.api.v1.FailJobRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flowgo.api.v1.FailJobRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.FailJobRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobKey: jspb.Message.getFieldWithDefault(msg, 1, 0),
    workerName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    retries: jspb.Message.getFieldWithDefault(msg, 3, 0),
    errorMessage: jspb.Message.getFieldWithDefault(msg, 4, ""),
    retryBackoffMs: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flowgo.api.v1.FailJobRequest}
 */
proto.flowgo.api.v1.FailJobRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flowgo.api.v1.FailJobRequest;
  return proto.flowgo.api.v1.FailJobRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flowgo.api.v1.FailJobRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flowgo.api.v1.FailJobRequest}
 */
proto.flowgo.api.v1.FailJobRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setJobKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkerName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRetries(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRetryBackoffMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flowgo.api.v1.FailJobRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flowgo.api.v1.FailJobRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flowgo.api.v1.FailJobRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.FailJobRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobKey();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getWorkerName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRetries();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRetryBackoffMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional int64 job_key = 1;
 * @return {number}
 */
proto.flowgo.api.v1.FailJobRequest.prototype.getJobKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.FailJobRequest} returns this
 */
proto.flowgo.api.v1.FailJobRequest.prototype.setJobKey = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string worker_name = 2;
 * @return {string}
 */
proto.flowgo.api.v1.FailJobRequest.prototype.getWorkerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.FailJobRequest} returns this
 */
proto.flowgo.api.v1.FailJobRequest.prototype.setWorkerName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 retries = 3;
 * @return {number}
 */
proto.flowgo.api.v1.FailJobRequest.prototype.getRetries = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.FailJobRequest} returns this
 */
proto.flowgo.api.v1.FailJobRequest.prototype.setRetries = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string error_message = 4;
 * @return {string}
 */
proto.flowgo.api.v1.FailJobRequest.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.flowgo.api.v1.FailJobRequest} returns this
 */
proto.flowgo.api.v1.FailJobRequest.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 retry_backoff_ms = 5;
 * @return {number}
 */
proto.flowgo.api.v1.FailJobRequest.prototype.getRetryBackoffMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.flowgo.api.v1.FailJobRequest} returns this
 */
proto.flowgo.api.v1.FailJobRequest.prototype.setRetryBackoffMs = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flowgo.api.v1.FailJobResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.flowgo.api.v1.FailJobResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flowgo.api.v1.FailJobResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.FailJobResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flowgo.api.v1.FailJobResponse}
 */
proto.flowgo.api.v1.FailJobResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flowgo.api.v1.FailJobResponse;
  return proto.flowgo.api.v1.FailJobResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flowgo.api.v1.FailJobResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flowgo.api.v1.FailJobResponse}
 */
proto.flowgo.api.v1.FailJobResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flowgo.api.v1.FailJobResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flowgo.api.v1.FailJobResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flowgo.api.v1.FailJobResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flowgo.api.v1.FailJobResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.flowgo.api.v1);
