#!/usr/bin/env bash
# test-all.sh — Full test suite orchestrator.
# Usage: bash scripts/test-all.sh
#   SKIP_DOWN=true   keep stack running after tests
#   SKIP_PERF=true   skip k6 performance tests (faster CI run)
#   SKIP_PLAYWRIGHT=true  skip browser E2E (headless Chromium not available)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORTS="${ROOT}/reports"
COMPOSE_CMD="${COMPOSE_CMD:-docker-compose}"
WAIT_TIMEOUT="${WAIT_TIMEOUT:-180}"
SKIP_DOWN="${SKIP_DOWN:-false}"
SKIP_PERF="${SKIP_PERF:-false}"
SKIP_PLAYWRIGHT="${SKIP_PLAYWRIGHT:-false}"

mkdir -p "${REPORTS}"

START_TIME="$(date +%s)"
SUMMARY_FILE="${REPORTS}/summary.md"

# ── helpers ────────────────────────────────────────────────────────────────

log()  { echo "[test-all] $*"; }
pass() { echo "✅ $*"; }
fail() { echo "❌ $*"; }

layer_result() {
  local name="$1" status="$2" detail="$3" duration="$4"
  printf "| %-22s | %s | %-40s | %ss |\n" "$name" "$status" "$detail" "$duration"
}

wait_http() {
  local url="$1" label="${2:-$1}"
  local start; start="$(date +%s)"
  log "Waiting for ${label}..."
  until curl -sS --max-time 5 -o /dev/null -w "%{http_code}" "${url}" 2>/dev/null | grep -qE '^[1-9][0-9]{2}$'; do
    local now; now="$(date +%s)"
    if (( now - start > WAIT_TIMEOUT )); then
      log "Timed out waiting for ${label}"
      return 1
    fi
    sleep 3
  done
  log "${label} is ready."
}

# ── clean up on exit ───────────────────────────────────────────────────────

cleanup() {
  if [[ "${SKIP_DOWN}" != "true" ]]; then
    log "Tearing down stack..."
    "${COMPOSE_CMD}" --profile full-cqrs down --remove-orphans 2>/dev/null || true
  fi
}
trap cleanup EXIT

# ── summary table header ───────────────────────────────────────────────────

{
  echo "# Test Report — $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo ""
  echo "Generated by \`make test-all\`."
  echo ""
  echo "| Layer | Status | Detail | Duration |"
  echo "|---|---|---|---|"
} > "${SUMMARY_FILE}"

append_row() { echo "$1" >> "${SUMMARY_FILE}"; }

# ═══════════════════════════════════════════════════════════════════════════
# STEP 1 — Start stack
# ═══════════════════════════════════════════════════════════════════════════

log "Starting docker-compose stack (full-cqrs)..."
"${COMPOSE_CMD}" --profile full-cqrs up -d --build

wait_http "http://localhost:8080/health" "workflow-command"
wait_http "http://localhost:8081/health" "workflow-query"
wait_http "http://localhost:8092/health" "sync-worker"

# ═══════════════════════════════════════════════════════════════════════════
# STEP 2 — Unit tests
# ═══════════════════════════════════════════════════════════════════════════

LAYER="Unit (Go)"
STEP_START="$(date +%s)"
log "Running unit tests..."

set +e
go test ./backend/... \
  -coverprofile="${REPORTS}/coverage.out" \
  -covermode=atomic \
  -json 2>&1 | tee "${REPORTS}/unit-raw.json"
UNIT_EXIT=$?
set -e

go tool cover -func="${REPORTS}/coverage.out" > "${REPORTS}/coverage.txt" 2>/dev/null || true

TOTAL_STMTS=$(grep -c "^" "${REPORTS}/coverage.txt" 2>/dev/null || echo 0)
COVERED=$(awk '/[1-9][0-9]*$/{c++} END{print c+0}' "${REPORTS}/coverage.txt" 2>/dev/null || echo 0)

# Generate coverage.json
python3 - "${REPORTS}/coverage.txt" "${REPORTS}/coverage.json" <<'PY'
import sys, json, re
cov_file = sys.argv[1]
out_file = sys.argv[2]
packages = {}
with open(cov_file) as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("total"):
            continue
        m = re.match(r'^(.+):\t\d+\t([\d.]+)%$', line)
        if m:
            pkg = m.group(1)
            pct = float(m.group(2))
            packages[pkg] = pct
total_line = [l for l in open(cov_file) if l.strip().startswith("total")]
total_pct = 0.0
if total_line:
    m = re.search(r'([\d.]+)%', total_line[-1])
    if m:
        total_pct = float(m.group(1))
with open(out_file, 'w') as f:
    json.dump({"total_coverage_pct": total_pct, "packages": packages}, f, indent=2)
PY

TOTAL_COVERAGE=$(python3 -c "import json; d=json.load(open('${REPORTS}/coverage.json')); print(f\"{d['total_coverage_pct']:.1f}%\")" 2>/dev/null || echo "n/a")
UNIT_DURATION=$(( $(date +%s) - STEP_START ))

if [[ $UNIT_EXIT -eq 0 ]]; then
  pass "Unit tests passed — coverage ${TOTAL_COVERAGE}"
  append_row "$(layer_result "${LAYER}" "✅ PASS" "coverage ${TOTAL_COVERAGE}" "${UNIT_DURATION}")"
else
  fail "Unit tests FAILED"
  append_row "$(layer_result "${LAYER}" "❌ FAIL" "see reports/unit-raw.json" "${UNIT_DURATION}")"
fi

# ═══════════════════════════════════════════════════════════════════════════
# STEP 3 — Integration tests
# ═══════════════════════════════════════════════════════════════════════════

LAYER="Integration (Go)"
STEP_START="$(date +%s)"
log "Running integration tests..."

set +e
go test ./tests/integration/... \
  -tags integration \
  -v \
  -json 2>&1 | tee "${REPORTS}/integration-raw.json"
INT_EXIT=$?
set -e

INT_PASS=$(python3 -c "import json,sys; d=[json.loads(l) for l in open('${REPORTS}/integration-raw.json') if l.strip()]; print(sum(1 for x in d if x.get('Action')=='pass' and x.get('Test')))" 2>/dev/null || echo 0)
INT_FAIL=$(python3 -c "import json,sys; d=[json.loads(l) for l in open('${REPORTS}/integration-raw.json') if l.strip()]; print(sum(1 for x in d if x.get('Action')=='fail' and x.get('Test')))" 2>/dev/null || echo 0)
INT_DURATION=$(( $(date +%s) - STEP_START ))

if [[ $INT_EXIT -eq 0 ]]; then
  pass "Integration tests passed — ${INT_PASS} passed, ${INT_FAIL} failed"
  append_row "$(layer_result "${LAYER}" "✅ PASS" "${INT_PASS} passed, ${INT_FAIL} failed" "${INT_DURATION}")"
else
  fail "Integration tests FAILED — ${INT_PASS} passed, ${INT_FAIL} failed"
  append_row "$(layer_result "${LAYER}" "❌ FAIL" "${INT_PASS} passed, ${INT_FAIL} failed" "${INT_DURATION}")"
fi

# ═══════════════════════════════════════════════════════════════════════════
# STEP 4 — E2E (bash scripts)
# ═══════════════════════════════════════════════════════════════════════════

LAYER="E2E Backend"
STEP_START="$(date +%s)"
log "Running E2E tests..."

set +e
bash "${ROOT}/scripts/test-e2e.sh" 2>&1 | tee "${REPORTS}/e2e-raw.txt"
E2E_EXIT=$?
set -e

E2E_DURATION=$(( $(date +%s) - STEP_START ))

if [[ $E2E_EXIT -eq 0 ]]; then
  pass "E2E backend tests passed"
  append_row "$(layer_result "${LAYER}" "✅ PASS" "cqrs_e2e + worker_conformance + parity" "${E2E_DURATION}")"
else
  fail "E2E backend tests FAILED"
  append_row "$(layer_result "${LAYER}" "❌ FAIL" "see reports/e2e-raw.txt" "${E2E_DURATION}")"
fi

# ═══════════════════════════════════════════════════════════════════════════
# STEP 5 — Frontend (Vitest)
# ═══════════════════════════════════════════════════════════════════════════

LAYER="Frontend (Vitest)"
STEP_START="$(date +%s)"
log "Running frontend unit tests..."

set +e
(cd "${ROOT}/frontend" && npm install --silent 2>/dev/null && \
  npx vitest run --reporter=json --outputFile="${REPORTS}/frontend-vitest.json" 2>&1 | \
  tee "${REPORTS}/frontend-vitest.txt")
FE_UNIT_EXIT=$?
set -e

FE_PASS=$(python3 -c "import json; d=json.load(open('${REPORTS}/frontend-vitest.json')); print(d.get('numPassedTests',0))" 2>/dev/null || echo 0)
FE_FAIL=$(python3 -c "import json; d=json.load(open('${REPORTS}/frontend-vitest.json')); print(d.get('numFailedTests',0))" 2>/dev/null || echo 0)
FE_UNIT_DURATION=$(( $(date +%s) - STEP_START ))

if [[ $FE_UNIT_EXIT -eq 0 ]]; then
  pass "Frontend unit tests passed — ${FE_PASS} passed"
  append_row "$(layer_result "${LAYER}" "✅ PASS" "${FE_PASS} passed, ${FE_FAIL} failed" "${FE_UNIT_DURATION}")"
else
  fail "Frontend unit tests FAILED — ${FE_PASS} passed, ${FE_FAIL} failed"
  append_row "$(layer_result "${LAYER}" "❌ FAIL" "${FE_PASS} passed, ${FE_FAIL} failed" "${FE_UNIT_DURATION}")"
fi

# ═══════════════════════════════════════════════════════════════════════════
# STEP 6 — Frontend (Playwright)
# ═══════════════════════════════════════════════════════════════════════════

if [[ "${SKIP_PLAYWRIGHT}" != "true" ]]; then
  LAYER="Frontend (Playwright)"
  STEP_START="$(date +%s)"
  log "Running Playwright E2E tests..."

  set +e
  (cd "${ROOT}/tests/e2e/playwright" && npm install --silent 2>/dev/null && \
    npx playwright install --with-deps chromium 2>/dev/null && \
    npx playwright test --reporter=json,line 2>&1 | \
    tee "${REPORTS}/playwright-raw.txt")
  PW_EXIT=$?
  set -e

  PW_DURATION=$(( $(date +%s) - STEP_START ))
  if [[ $PW_EXIT -eq 0 ]]; then
    pass "Playwright E2E passed"
    append_row "$(layer_result "${LAYER}" "✅ PASS" "browser E2E all passed" "${PW_DURATION}")"
  else
    fail "Playwright E2E FAILED"
    append_row "$(layer_result "${LAYER}" "❌ FAIL" "see reports/playwright-raw.txt" "${PW_DURATION}")"
  fi
else
  log "Skipping Playwright (SKIP_PLAYWRIGHT=true)"
  append_row "$(layer_result "Frontend (Playwright)" "⏭ SKIP" "SKIP_PLAYWRIGHT=true" "0")"
fi

# ═══════════════════════════════════════════════════════════════════════════
# STEP 7 — Performance (k6)
# ═══════════════════════════════════════════════════════════════════════════

if [[ "${SKIP_PERF}" != "true" ]]; then
  LAYER="Performance (k6)"
  STEP_START="$(date +%s)"
  log "Running k6 performance tests..."

  set +e
  docker run --rm --network host \
    -v "${ROOT}/tests/performance/k6:/scripts" \
    -v "${REPORTS}:/reports" \
    grafana/k6:latest run \
      --out json=/reports/k6.json \
      /scripts/run-all.js 2>&1 | tee "${REPORTS}/perf-raw.txt"
  PERF_EXIT=$?
  set -e

  PERF_DURATION=$(( $(date +%s) - STEP_START ))

  P95=$(python3 -c "
import json
with open('${REPORTS}/k6.json') as f:
    for line in f:
        d = json.loads(line)
        if d.get('type')=='Point' and d.get('metric')=='http_req_duration' and d.get('data',{}).get('tags',{}).get('percentile')=='p(95)':
            print(f\"{d['data']['value']:.0f}ms\")
            break
    else:
        print('n/a')
" 2>/dev/null || echo "n/a")

  if [[ $PERF_EXIT -eq 0 ]]; then
    pass "Performance tests passed — p95≈${P95}"
    append_row "$(layer_result "${LAYER}" "✅ PASS" "p95≈${P95}, thresholds met" "${PERF_DURATION}")"
  else
    fail "Performance tests FAILED or threshold breached"
    append_row "$(layer_result "${LAYER}" "❌ FAIL" "see reports/perf-raw.txt" "${PERF_DURATION}")"
  fi
else
  log "Skipping performance tests (SKIP_PERF=true)"
  append_row "$(layer_result "Performance (k6)" "⏭ SKIP" "SKIP_PERF=true" "0")"
fi

# ═══════════════════════════════════════════════════════════════════════════
# STEP 8 — Security
# ═══════════════════════════════════════════════════════════════════════════

LAYER="Security"
STEP_START="$(date +%s)"
log "Running security tests..."

set +e
bash "${ROOT}/scripts/test-security.sh" 2>&1 | tee "${REPORTS}/security-raw.txt"
SEC_EXIT=$?
set -e

SEC_DURATION=$(( $(date +%s) - STEP_START ))

if [[ $SEC_EXIT -eq 0 ]]; then
  pass "Security tests passed"
  append_row "$(layer_result "${LAYER}" "✅ PASS" "govulncheck + gosec + trivy" "${SEC_DURATION}")"
else
  pass "Security tests completed with findings"
  append_row "$(layer_result "${LAYER}" "⚠️  WARN" "findings — see reports/security.md" "${SEC_DURATION}")"
fi

# ═══════════════════════════════════════════════════════════════════════════
# STEP 9 — Generate per-layer detail reports + summary footer
# ═══════════════════════════════════════════════════════════════════════════

bash "${ROOT}/scripts/test-report.sh"

TOTAL_DURATION=$(( $(date +%s) - START_TIME ))
{
  echo ""
  echo "---"
  echo "_Total wall-clock time: ${TOTAL_DURATION}s_"
  echo ""
  echo "Reports: \`$(realpath "${REPORTS}")\`"
} >> "${SUMMARY_FILE}"

log ""
log "═══════════════════════════════════════"
log "All tests complete in ${TOTAL_DURATION}s"
log "Report: ${SUMMARY_FILE}"
log "═══════════════════════════════════════"
cat "${SUMMARY_FILE}"
